apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-boot-mysql-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-boot-mysql-app
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  build:
      env:
      - name: BP_JVM_VERSION
        value: "17.*"
  serviceClaims:
  - name: db
    # The preferred way to bind to a service is to use a ResourceClaim
    # The MySQL Service documentation however does not yet reflect this
    # 
    # ref:
    #   apiVersion: with.sql.tanzu.vmware.com/v1
    #   kind: MySQL
    #   name: mysql-db
    ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mysql-db